export const BLACK = '#07404d'
export const TURQUOISE = '#04c6f1'
export const DARK_GRAY = '#5b7379'
export const DARK_TURQUOISE = '#0e758c'
export const GRAY = '#c2c8ca'
export const WHITE = '#fefefe'
export const WHITE_SMOKE = '#fcfcfc'
