export const ActionType = {
  SET_HL_GRADE: 'SET_HL_GRADE',
  SET_HA_GRADE: 'SET_HA_GRADE',
  SET_HA_NUM_NOISE_BITS: 'SET_HA_NUM_NOISE_BITS',

  SET_TARGET: 'SET_TARGET',
  SET_MASK: 'SET_MASK',

  SET_TARGET_POSITION: 'SET_TARGET_POSITION',
  SET_TARGET_VOLUME: 'SET_TARGET_VOLUME',
  SET_PERFORMANE_MODE_ENABLED: 'SET_PERFORMANE_MODE_ENABLED',
  SET_HEAD_RADIUS: 'SET_HEAD_RADIUS',
  SET_DIRECTIONALITY_ENABLED: 'SET_DIRECTIONALITY_ENABLED',
  SET_DIRECTIONALITY_ATTENUATION: 'SET_DIRECTIONALITY_ATTENUATION',
  SET_MASK_VOLUME: 'SET_MASK_VOLUME',
  SET_PLAYBACK_STATE: 'SET_PLAYBACK_STATE',
}

export const AudioFileType = {
  SPLIT: 'SPLIT',
  STEREO: 'STEREO',
}

export const Ear = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
}

export const HearingLossGrade = {
  NONE: 'NONE',
  MILD: 'MILD',
  MODERATE: 'MODERATE',
  SEVERE: 'SEVERE',
}

export const SimulatorType = {
  AID: 'AID',
  LOSS: 'LOSS',
}

export const SonicComponent = {
  TARGET: 'TARGET',
  MASK: 'MASK',
}

export const PlaybackState = {
  PAUSED: 'PAUSED',
  PLAYING: 'PLAYING',
}
