export const ActionType = {
  SET_DISCLAIMER_READ: 'SET_DISCLAIMER_READ',
  SET_PRESET_INFO_DISMISSED: 'SET_PRESET_INFO_DISMISSED',

  SET_HL_ENABLED: 'SET_HL_ENABLED',
  SET_HL_LINKED: 'SET_HL_LINKED',
  SET_HL_GRADE: 'SET_HL_GRADE',
  SET_HL_FREQUENCY_SMEARING_PRESET: 'SET_HL_FREQUENCY_SMEARING_PRESET',
  SET_HL_TEMPORAL_DISTORTION_PRESET: 'SET_HL_TEMPORAL_DISTORTION_PRESET',

  SET_HA_ENABLED: 'SET_HA_ENABLED',
  SET_HA_LINKED: 'SET_HA_LINKED',
  SET_HA_GRADE: 'SET_HA_GRADE',
  SET_QUANTISATION_STEP_ENABLED: 'SET_QUANTISATION_STEP_ENABLED',
  SET_HA_NUM_NOISE_BITS: 'SET_HA_NUM_NOISE_BITS',

  SET_TARGET: 'SET_TARGET',
  SET_MASK: 'SET_MASK',

  SET_TARGET_POSITION: 'SET_TARGET_POSITION',
  SET_TARGET_ELEVATION: 'SET_TARGET_ELEVATION',
  SET_TARGET_VOLUME: 'SET_TARGET_VOLUME',
  SET_PERFORMANE_MODE_ENABLED: 'SET_PERFORMANE_MODE_ENABLED',
  SET_HEAD_RADIUS: 'SET_HEAD_RADIUS',
  SET_DIRECTIONALITY_ENABLED: 'SET_DIRECTIONALITY_ENABLED',
  SET_DIRECTIONALITY_VALUE: 'SET_DIRECTIONALITY_VALUE',
  SET_MASK_VOLUME: 'SET_MASK_VOLUME',
  SET_PLAYBACK_STATE: 'SET_PLAYBACK_STATE',

  SET_HRTF: 'SET_HRTF',

  SET_GLOBAL_PRESET: 'SET_GLOBAL_PRESET',

  ADD_PROMPT: 'ADD_PROMPT',
  RESOLVE_PROMPT: 'RESOLVE_PROMPT',
}

export const AudioFileType = {
  SPLIT: 'SPLIT',
  STEREO: 'STEREO',
}

export const Ear = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
}

export const GlobalPreset = {
  NONE: 'NONE',
  MILD_HEARING_LOSS: 'MILD_HEARING_LOSS',
  MONOLATERAL_MILD_HEARING_LOSS: 'MONOLATERAL_MILD_HEARING_LOSS',
  MILD_HEARING_LOSS_WITH_HEARING_AID: 'MILD_HEARING_LOSS_WITH_HEARING_AID',
  MODERATE_HEARING_LOSS_WITH_DISTORTION:
    'MODERATE_HEARING_LOSS_WITH_DISTORTION',
  MODERATE_HEARING_LOSS_WITH_DISTORTION_AND_HEARING_AID:
    'MODERATE_HEARING_LOSS_WITH_DISTORTION_AND_HEARING_AID',
}

export const HearingLossGrade = {
  NONE: 'NONE',
  MILD: 'MILD',
  MODERATE: 'MODERATE',
  SEVERE: 'SEVERE',
}

export const QuantisationStep = {
  BEFORE: 'BEFORE',
  AFTER: 'AFTER',
}

export const PlaybackState = {
  PAUSED: 'PAUSED',
  PLAYING: 'PLAYING',
}

export const PromptStatus = {
  UNRESOLVED: 'UNRESOLVED',
  REJECTED: 'REJECTED',
  RESOLVED: 'RESOLVED',
}

export const SimulatorType = {
  AID: 'AID',
  LOSS: 'LOSS',
  FREQUENCY_SMEARING: 'FREQUENCY_SMEARING',
  TEMPORAL_DISTORTION: 'TEMPORAL_DISTORTION',
}

export const SonicComponent = {
  TARGET: 'TARGET',
  MASK: 'MASK',
}
